# https://jupyterbook.org/en/stable/customize/config.html

# Book settings
title: Open223 Documentation
author: ""
copyright: ""
logo: ""

# Execution settings
execute:
  execute_notebooks: force

# Parse and render settings


# HTML-specific settings
html:
  use_repository_button: true
  use_issues_button: true

# LaTeX-specific settings


# Launch button settings
repository:
  url: https://github.com/open223/docs.open223.info
  branch: main

# Advanced and power-user settings
