# https://jupyterbook.org/en/stable/customize/config.html

# Book settings
title: Open223 Documentation
author: ""
copyright: ""
logo: ""

# Execution settings
execute:
  execute_notebooks: force

# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

# HTML-specific settings
html:
  use_repository_button: true
  use_issues_button: true

# LaTeX-specific settings


# Launch button settings
repository:
  url: https://github.com/open223/docs.open223.info
  branch: main

# Advanced and power-user settings
sphinx:
  extra_extensions:
    - sphinxcontrib.mermaid
  config:
    html_extra_path: ['model_vis']
